// ═══════════════════════════════════════════════════════════════════
//  _prelude.wgsl — canonical binding header
//
//  GENERATED by scripts/generate_shader_libs.py from
//  scripts/bindgroup_checker.py EXPECTED_BINDINGS and
//  src/contracts/uniforms_layout.json. Do not hand-edit:
//  `npm run verify:wgsl-include` regenerates and compares.
//
//  Use it with:
//      #include "_prelude.wgsl"
//
//  Binding 13 (historyTexture) is optional and NOT declared here — the 11
//  shaders that use it declare it themselves, because a shader that binds it
//  without reading it is a validation error.
// ═══════════════════════════════════════════════════════════════════

@group(0) @binding(0) var u_sampler: sampler;
@group(0) @binding(1) var readTexture: texture_2d<f32>;
@group(0) @binding(2) var writeTexture: texture_storage_2d<rgba32float, write>;
@group(0) @binding(3) var<uniform> u: Uniforms;
@group(0) @binding(4) var readDepthTexture: texture_2d<f32>;
@group(0) @binding(5) var non_filtering_sampler: sampler;
@group(0) @binding(6) var writeDepthTexture: texture_storage_2d<r32float, write>;
@group(0) @binding(7) var dataTextureA: texture_storage_2d<rgba32float, write>;
@group(0) @binding(8) var dataTextureB: texture_storage_2d<rgba32float, write>;
@group(0) @binding(9) var dataTextureC: texture_2d<f32>;
@group(0) @binding(10) var<storage, read_write> extraBuffer: array<f32>;
@group(0) @binding(11) var comparison_sampler: sampler_comparison;
@group(0) @binding(12) var<storage, read> plasmaBuffer: array<vec4<f32>>;

// Field meanings are contract, not convention — see src/contracts/uniforms_layout.json.
//   config.x      time in seconds since renderer start (monotonic, NOT delta time)
//   config.y      rippleCount, 0..50 — guard loops with min(u32(u.config.y), 50u)
//   config.zw     render-target resolution in pixels
//   zoom_config.x time again (same value as config.x)
//   zoom_config.yz mouse uv in 0..1, y=0 at the top
//   zoom_config.w mouse_down, pressed when > 0.5
//   zoom_params   user params p1..p4 from the UI sliders
//   ripples[i].xy uv, .z startTime in seconds, .w padding (always 0)

struct Uniforms {
  config: vec4<f32>,              // .x = time (seconds), .y = rippleCount (0-50 active ripples), .zw = resolution (width, height)
  zoom_config: vec4<f32>,         // .x = time, .yz = mouse_uv (0-1 canvas: y=0 top), .w = mouse_down (>0.5 = pressed)
  zoom_params: vec4<f32>,         // .xyzw = user params p1..p4 (mapped from UI sliders)
  ripples: array<vec4<f32>, 50>,  // .xy = ripple uv, .z = startTime (seconds), .w = padding (0)
};
