// ═══════════════════════════════════════════════════════════════════
//  cyber-rain-em
//  Category: advanced-hybrid
//  Features: mouse-driven, cyber-rain, electromagnetic-field, chromatic
//  Complexity: High
//  Chunks From: cyber-rain.wgsl, mouse-electromagnetic-aurora.wgsl
//  Created: 2026-04-18
//  By: Agent CB-18
// ═══════════════════════════════════════════════════════════════════
//  Cyber rain falls through an electromagnetic field generated by the
//  mouse. Electric fields distort rain trajectories; magnetic fields
//  rotate raindrop hues. The wiper/shield effect clears both rain and
//  field lines. Alpha stores field magnitude.
// ═══════════════════════════════════════════════════════════════════

@group(0) @binding(0) var u_sampler: sampler;
@group(0) @binding(1) var readTexture: texture_2d<f32>;
@group(0) @binding(2) var writeTexture: texture_storage_2d<rgba32float, write>;
@group(0) @binding(3) var<uniform> u: Uniforms;
@group(0) @binding(4) var readDepthTexture: texture_2d<f32>;
@group(0) @binding(5) var non_filtering_sampler: sampler;
@group(0) @binding(6) var writeDepthTexture: texture_storage_2d<r32float, write>;
@group(0) @binding(7) var dataTextureA: texture_storage_2d<rgba32float, write>;
@group(0) @binding(8) var dataTextureB: texture_storage_2d<rgba32float, write>;
@group(0) @binding(9) var dataTextureC: texture_2d<f32>;
@group(0) @binding(10) var<storage, read_write> extraBuffer: array<f32>;
@group(0) @binding(11) var comparison_sampler: sampler_comparison;
@group(0) @binding(12) var<storage, read> plasmaBuffer: array<vec4<f32>>;

struct Uniforms {
  config: vec4<f32>,
  zoom_config: vec4<f32>,
  zoom_params: vec4<f32>,
  ripples: array<vec4<f32>, 50>,
};

fn hash12(p: vec2<f32>) -> f32 {
  var p3 = fract(vec3<f32>(p.xyx) * 0.1031);
  p3 = p3 + dot(p3, p3.yzx + 33.33);
  return fract((p3.x + p3.y) * p3.z);
}

fn hueShift(color: vec3<f32>, hue: f32) -> vec3<f32> {
  let k = vec3<f32>(0.57735, 0.57735, 0.57735);
  let cosAngle = cos(hue);
  return color * cosAngle + cross(k, color) * sin(hue) + k * dot(k, color) * (1.0 - cosAngle);
}

fn electricField(pos: vec2<f32>, chargePos: vec2<f32>, charge: f32) -> vec2<f32> {
  let r = pos - chargePos;
  let dist = max(length(r), 0.001);
  return charge * normalize(r) / (dist * dist);
}

fn magneticField(pos: vec2<f32>, chargePos: vec2<f32>, velocity: vec2<f32>, charge: f32) -> f32 {
  let r = pos - chargePos;
  let dist = max(length(r), 0.001);
  return charge * (velocity.x * r.y - velocity.y * r.x) / (dist * dist * dist);
}

@compute @workgroup_size(16, 16, 1)
fn main(@builtin(global_invocation_id) global_id: vec3<u32>) {
  let resolution = u.config.zw;
  if (global_id.x >= u32(resolution.x) || global_id.y >= u32(resolution.y)) {
    return;
  }
  let uv = vec2<f32>(global_id.xy) / resolution;
  let aspect = resolution.x / resolution.y;
  let time = u.config.x;

  let rainIntensity = u.zoom_params.x;
  let chargeStrength = u.zoom_params.y * 2.0;
  let fieldVis = u.zoom_params.z;
  let wiperSize = u.zoom_params.w * 0.5;

  let mousePos = u.zoom_config.yz;
  let prevMouse = textureLoad(dataTextureC, vec2<i32>(0, 0), 0).xy;
  let mouseVel = (mousePos - prevMouse) * 60.0;

  if (global_id.x == 0u && global_id.y == 0u) {
    textureStore(dataTextureA, vec2<i32>(0, 0), vec4<f32>(mousePos, 0.0, 0.0));
  }

  // Wiper / Shield
  let distVec = (uv - mousePos) * vec2<f32>(aspect, 1.0);
  let dist = length(distVec);
  let wiper = smoothstep(wiperSize, wiperSize * 0.8, dist);

  // EM Fields
  let eField = electricField(uv, mousePos, chargeStrength);
  let bField = magneticField(uv, mousePos, mouseVel, chargeStrength);

  var totalE = eField;
  var totalB = bField;
  let rippleCount = min(u32(u.config.y), 50u);
  for (var i: u32 = 0u; i < rippleCount; i = i + 1u) {
    let ripple = u.ripples[i];
    let elapsed = time - ripple.z;
    if (elapsed > 0.0 && elapsed < 3.0) {
      let orbitAngle = elapsed * 2.0 + f32(i) * 1.256;
      let orbitRadius = 0.05 + 0.1 * smoothstep(0.0, 1.0, elapsed);
      let orbitPos = mousePos + vec2<f32>(cos(orbitAngle), sin(orbitAngle)) * orbitRadius;
      let secondaryCharge = -chargeStrength * exp(-elapsed * 0.8);
      let secVel = vec2<f32>(-sin(orbitAngle), cos(orbitAngle)) * 2.0;
      totalE = totalE + electricField(uv, orbitPos, secondaryCharge);
      totalB = totalB + magneticField(uv, orbitPos, secVel, secondaryCharge);
    }
  }

  let fieldMag = length(totalE);
  let fieldDir = select(vec2<f32>(0.0), normalize(totalE), fieldMag > 0.0001);

  // Vertical blur with field distortion
  var blurredColor = vec4<f32>(0.0);
  let samples = 5;
  let blurStrength = rainIntensity * 0.08;
  for (var i = 0; i < samples; i++) {
    let offset = f32(i) * blurStrength * (1.0 - wiper);
    let sampleUV = uv + vec2<f32>(fieldDir.x * offset * 2.0, offset - blurStrength * 2.0);
    let col = textureSampleLevel(readTexture, u_sampler, clamp(sampleUV, vec2<f32>(0.0), vec2<f32>(1.0)), 0.0);
    let brightness = max(col.r, max(col.g, col.b));
    let bloom = smoothstep(0.6, 1.0, brightness);
    blurredColor += col * (1.0 + bloom * 2.0);
  }
  blurredColor = blurredColor / f32(samples);

  let baseColor = textureSampleLevel(readTexture, u_sampler, uv, 0.0);
  var finalColor = mix(baseColor, blurredColor, rainIntensity * 0.8);

  // Rain drops with EM displacement
  let rainUV = uv * vec2<f32>(20.0, 2.0) + vec2<f32>(fieldDir.x * fieldMag * 5.0, time * 10.0 * rainIntensity);
  let rainNoise = hash12(floor(rainUV));
  let drop = smoothstep(0.9, 0.95, rainNoise) * rainIntensity;
  let rainMask = 1.0 - wiper;

  // Rain color with magnetic hue rotation
  let rainColor = vec3<f32>(0.5, 0.7, 1.0);
  let rotatedRain = hueShift(rainColor, totalB * 2.0);
  finalColor += vec4<f32>(rotatedRain, 0.0) * drop * rainMask;

  // Field line overlay
  let streamUV = uv + fieldDir * hash12(uv * 100.0 + time * 0.5) * 0.02;
  let streamNoise = hash12(streamUV * 200.0 + fieldMag * 10.0);
  let streamline = smoothstep(0.4, 0.6, streamNoise) * fieldVis * smoothstep(0.0, 0.5, fieldMag);
  let fieldColor = mix(vec3<f32>(0.0, 0.6, 1.0), vec3<f32>(1.0, 0.8, 0.0), atan2(fieldDir.y, fieldDir.x) * 0.159 + 0.5);
  finalColor = vec4<f32>(mix(finalColor.rgb, fieldColor, streamline * 0.4), finalColor.a);

  // Core glow
  let mouseDist = length((uv - mousePos) * vec2<f32>(aspect, 1.0));
  let coreGlow = exp(-mouseDist * mouseDist * 400.0) * chargeStrength;
  finalColor += vec4<f32>(0.6, 0.9, 1.0, 0.0) * coreGlow * fieldVis;

  let alpha = clamp(totalB * 0.5 + 0.5, 0.0, 1.0);

  textureStore(writeTexture, vec2<i32>(global_id.xy), vec4<f32>(finalColor.rgb, alpha));

  let d = textureSampleLevel(readDepthTexture, non_filtering_sampler, uv, 0.0).r;
  textureStore(writeDepthTexture, global_id.xy, vec4<f32>(d, 0.0, 0.0, 0.0));
}
