// Auto-generated by scripts/generate-shader-definition-types.mjs from
// src/contracts/shader_definition.schema.json. Do not edit — change the schema and re-run.
export type ShaderDefinitionGraphRole =
  | 'read'
  | 'color'
  | 'dataA'
  | 'dataB'
  | 'dataC'
  | 'simState'
  | 'simIndex';

/**
 * One shader_definitions/<category>/<id>.json file. Source of truth for the catalog: scripts/generate_shader_lists.js copies it into public/shader-lists/<category>.json (minus x-meta). Cross-field rules JSON Schema cannot express (id == file stem, id/url stem, category == folder, unique param ids, default within [min, max]) live in scripts/validate_shader_definitions.mjs. TypeScript type: src/types/ShaderDefinition.ts (generated).
 */
export interface ShaderDefinition {
  /**
   * Catalog id. Kebab-case; 22 legacy ids keep underscores (hyphen aliases in shader-id-aliases.json).
   */
  id: string;
  name: string;
  /**
   * WGSL path under public/. Relative; 19 legacy files keep a leading slash.
   */
  url: string;
  description?: string;
  tags?: string[];
  features?: string[];
  /**
   * Redundant with the folder (the generator uses the folder). If present it must equal the folder; validate_shader_definitions.mjs enforces that.
   */
  category?:
    | 'advanced-hybrid'
    | 'artistic'
    | 'distortion'
    | 'generative'
    | 'geometric'
    | 'hybrid'
    | 'image'
    | 'interactive-mouse'
    | 'lighting-effects'
    | 'liquid-effects'
    | 'post-processing'
    | 'retro-glitch'
    | 'simulation'
    | 'visual-effects';
  /**
   * UI sliders, in zoom_params slot order unless mapping says otherwise.
   */
  params?: ShaderDefinitionParam[];
  multipass?: ShaderDefinitionMultipass;
  simRing?: ShaderDefinitionSimRing;
  /**
   * @minItems 3
   * @maxItems 3
   */
  workgroup_size?: [number, number, number];
  supportsDepth?: boolean;
  supportsDof?: boolean;
  /**
   * How dataTextureA/B/C are packed for feedback shaders.
   */
  feedbackPacking?: string;
  /**
   * Where cross-frame state lives (extraBuffer ranges etc.).
   */
  persistentState?: string;
  /**
   * Shader needs @workgroup_size(16,16,4) = 1024 invocations.
   */
  requiresDeepWorkgroup?: boolean;
  /**
   * Shader samples binding 13 (historyTexture 2d-array ring).
   */
  requiresHistoryRing?: boolean;
  /**
   * Shader needs rgba32float storage (physics / RD sims).
   */
  requiresRgba32Float?: boolean;
  audioReactive?: boolean;
  mouseReactive?: boolean;
  /**
   * Swarm marker: shader went through an upgrade pass.
   */
  updated?: boolean;
  type?: 'generative' | 'compute';
  /**
   * Position on the shader-coordinate quality axis.
   */
  coordinate?: number;
  icon?: string;
  label?: string;
  'x-meta'?: ShaderDefinitionMeta;
}
export interface ShaderDefinitionParam {
  id: string;
  name: string;
  default: number;
  min: number;
  max: number;
  step?: number;
  /**
   * WGSL uniform lane this slider drives, e.g. zoom_params.x.
   */
  mapping?: string;
  /**
   * Audio source that drives this slider in audio-reactive mode: a named band, or an FFT bin.
   */
  audio?:
    | ('bass' | 'mid' | 'treble' | 'overall')
    | {
        fft: number;
      };
  description?: string;
  /**
   * Names for the steps of a discrete slider.
   */
  labels?: string[];
}
/**
 * Linear chain (pass/totalPasses/next|prevShader), a Tier C graph, or both.
 */
export interface ShaderDefinitionMultipass {
  pass?: number;
  totalPasses?: number;
  nextShader?: string | null;
  prevShader?: string | null;
  passes?: {
    pass: number;
    name?: string;
    file: string;
  }[];
  graph?: ShaderDefinitionGraph;
}
/**
 * Mirrors MultipassGraphDef in src/renderer/multipassGraph.ts.
 */
export interface ShaderDefinitionGraph {
  maxPassesPerFrame: number;
  nodes: {
    id: string;
    entry: string;
    reads: ShaderDefinitionGraphRole[];
    writes: ShaderDefinitionGraphRole[];
    repeat?: number;
    dispatch?: 'pixels' | 'simState';
    scalable?: boolean;
    minScale?: 0.25 | 0.5 | 0.75 | 1;
  }[];
}
/**
 * Opt-in @group(1) sim-ring request (see bind_group1.json). Only stateCount is consumed.
 */
export interface ShaderDefinitionSimRing {
  stateCount: number;
  agent?: string;
  packing?: string;
}
/**
 * Authoring / swarm provenance. The app never reads it and generate_shader_lists.js strips it from public/shader-lists. Anything that is not shader behaviour belongs here, not at the top level.
 */
export interface ShaderDefinitionMeta {
  seeded_by?: string;
  chunks_used?: string[];
  target_rating?: number;
  performance_target?: string;
  wolfram_params?: {
    [k: string]: string;
  };
  created_by?: string;
  created_date?: string;
  author?: string;
  complexity?: string;
  filename?: string;
  /**
   * Swarm upgrade pass output. `params` is the index-keyed slider list the upgrade scripts write (formerly top-level updatedParams).
   */
  upgrade?: {
    params?: unknown[];
    [k: string]: unknown;
  };
  /**
   * Redundant pre-schema containers kept verbatim (parameters / controls / advanced_params / uniforms / passes) when `params` already existed.
   */
  legacy?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
