import { RenderMode, ShaderEntry, ShaderCategory, InputSource, SlotParams } from '../../renderer/types';
import { AIStatus, AutoTransitionConfig } from '../../AutoDJ';
import { VideoRecord } from '../../syncTypes';
import type { SharedChain } from '../../services/layerChainShare';
import type { RenderQualityMode } from '../../config/performancePolicy';

export interface ShaderCoordData {
    coordinate: number;
    name: string;
    category: string;
    features: string[];
    tags: string[];
}

export interface ControlsProps {
    modes: RenderMode[];
    setMode: (index: number, mode: RenderMode) => void;
    activeSlot: number;
    setActiveSlot: (index: number) => void;
    slotParams: SlotParams[];
    updateSlotParam: (slotIndex: number, updates: Partial<SlotParams>) => void;
    slotShaderStatus?: Array<'idle' | 'loading' | 'error'>;
    shaderCategory: ShaderCategory;
    setShaderCategory: (category: ShaderCategory) => void;
    onNewImage: () => void;
    autoChangeEnabled: boolean;
    setAutoChangeEnabled: (enabled: boolean) => void;
    autoChangeDelay: number;
    setAutoChangeDelay: (delay: number) => void;
    onLoadModel: () => void;
    isModelLoaded: boolean;
    availableModes: ShaderEntry[];
    inputSource: InputSource;
    setInputSource: (source: InputSource) => void;
    videoList: VideoRecord[];
    selectedVideo: string;
    setSelectedVideo: (video: string) => void;
    videoB3hdMode?: boolean;
    setVideoB3hdMode?: (enabled: boolean) => void;
    b3hdSegmentLength?: number;
    setB3hdSegmentLength?: (len: number) => void;
    b3hdIntervalSeconds?: number;
    setB3hdIntervalSeconds?: (sec: number) => void;
    currentSegment?: { video: VideoRecord; start: number; end: number } | null;
    isMuted: boolean;
    setIsMuted: (muted: boolean) => void;
    onUploadImageTrigger: () => void;
    onUploadVideoTrigger: () => void;
    activeGenerativeShader?: string;
    setActiveGenerativeShader?: (id: string) => void;
    isAiVjMode: boolean;
    onToggleAiVj: () => void;
    aiVjStatus: AIStatus;
    aiVjMessage?: string;
    onGenerateFromVibe?: (vibe: string) => void;
    onUpdateStack?: (ids: string[]) => void;
    onUpdateParams?: (params: Record<string, number>[]) => void;
    onRandomizeParams?: () => void;
    onSavePreset?: (name: string) => void;
    onShareVjSet?: () => void;
    onSaveVjSet?: (name: string) => void;
    onStartAutoTransition?: (config: AutoTransitionConfig) => Promise<boolean> | boolean;
    onStopAutoTransition?: () => void;
    isWebcamActive?: boolean;
    onStartWebcam?: () => void;
    onStopWebcam?: () => void;
    webcamError?: string | null;
    showWebcamShaderSuggestions?: boolean;
    webcamFunShaders?: string[];
    onApplyWebcamShader?: (shaderId: string) => void;
    onRoulette?: () => void;
    onRandomizeAllSlots?: () => void;
    isRouletteActive?: boolean;
    chaosModeEnabled?: boolean;
    setChaosModeEnabled?: (enabled: boolean) => void;
    audioReactiveParams?: boolean;
    setAudioReactiveParams?: (enabled: boolean) => void;
    audioReactiveAmount?: number;
    setAudioReactiveAmount?: (amount: number) => void;
    isRecording?: boolean;
    recordingCountdown?: number;
    onStartRecording?: () => void;
    onStopRecording?: () => void;
    onTakeScreenshot?: () => void;
    liveStreamUrl?: string;
    onLiveStreamLoaded?: (url: string) => void;
    onExitLiveStream?: () => void;
    onOpenShaderScanner?: () => void;
    activeRendererType?: 'webgpu' | 'wasm' | 'js';
    onSwitchRenderer?: (type: 'webgpu' | 'wasm' | 'js') => Promise<void>;
    onOpenStorageBrowser?: () => void;
    onCopyChainShareLink?: () => void;
    onApplySharedChain?: (chain: SharedChain) => void;
    getCurrentChain?: () => SharedChain | null;
    onTriggerNextTransition?: () => Promise<void> | void;
    onRandomizeSlot?: (slot: number) => void;
    onSetSlotParam?: (slot: number, param: string, value: number) => void;
    renderQualityMode?: RenderQualityMode;
    onRenderQualityChange?: (mode: RenderQualityMode) => void;
    maxActiveSlots?: number;
    performanceHud?: {
        internalWidth: number;
        internalHeight: number;
        scale: number;
        targetFps: number;
        adaptive: boolean;
    };
}
