import React, { useState, useMemo, useEffect, useRef, useCallback } from 'react';
import { createPortal } from 'react-dom';
import { ShaderMegaMenuOption } from './ShaderMegaMenu';
import { ShaderStarRating } from './ShaderStarRating';
import './ShaderGallery.css';

export interface ShaderGalleryProps {
  /** Flat list of shaders to browse (already filtered to the desired categories). */
  options: ShaderMegaMenuOption[];
  /** Currently selected shader id. */
  value?: string;
  /** Called with the chosen shader id. */
  onSelect: (id: string) => void;
  /** Called to close the gallery (e.g. backdrop click / Escape / explicit close button). */
  onClose: () => void;
}

interface ThumbnailManifestEntry {
  thumbnail_url: string;
  generated_at: string;
  params_snapshot?: number[];
}

type ThumbnailManifest = Record<string, ThumbnailManifestEntry>;

const CATEGORY_LABELS: Record<string, string> = {
  'interactive-mouse': '🖱️ Interactive',
  'artistic': '🎨 Artistic',
  'generative': '✨ Generative',
  'distortion': '🔮 Distortion',
  'image': '🖼️ Image',
  'visual-effects': '🎬 Visual Effects',
  'retro-glitch': '📺 Retro / Glitch',
  'liquid-effects': '💧 Liquid',
  'simulation': '🧬 Simulation',
  'geometric': '📐 Geometric',
  'lighting-effects': '💡 Lighting',
};

/** Number of grid items rendered initially / per "load more" batch. */
const BATCH_SIZE = 60;

export const ShaderGallery: React.FC<ShaderGalleryProps> = ({ options, value, onSelect, onClose }) => {
  const [manifest, setManifest] = useState<ThumbnailManifest>({});
  const [search, setSearch] = useState('');
  const [category, setCategory] = useState('');
  const [visibleCount, setVisibleCount] = useState(BATCH_SIZE);
  const sentinelRef = useRef<HTMLDivElement>(null);

  // Load the static thumbnail manifest generated by
  // scripts/generate-shader-thumbnails.js (Phase 1 batch render).
  useEffect(() => {
    fetch('./thumbnails/manifest.json')
      .then(r => (r.ok ? r.json() : {}))
      .then(setManifest)
      .catch(() => setManifest({}));
  }, []);

  const categories = useMemo(() => {
    const set = new Set<string>();
    for (const o of options) set.add(o.category || 'other');
    return Array.from(set);
  }, [options]);

  const filtered = useMemo(() => {
    const q = search.toLowerCase();
    return options.filter(o => {
      if (category && (o.category || 'other') !== category) return false;
      if (q && !o.name.toLowerCase().includes(q) && !o.id.toLowerCase().includes(q)) return false;
      return true;
    });
  }, [options, search, category]);

  // Reset pagination when filters change
  useEffect(() => {
    setVisibleCount(BATCH_SIZE);
  }, [search, category]);

  const visible = filtered.slice(0, visibleCount);
  const hasMore = visibleCount < filtered.length;

  // Infinite scroll: grow visibleCount when the sentinel enters view
  const loadMore = useCallback(() => {
    setVisibleCount(c => Math.min(c + BATCH_SIZE, filtered.length));
  }, [filtered.length]);

  useEffect(() => {
    if (!hasMore) return;
    const el = sentinelRef.current;
    if (!el) return;
    const observer = new IntersectionObserver(entries => {
      if (entries[0]?.isIntersecting) loadMore();
    }, { rootMargin: '400px' });
    observer.observe(el);
    return () => observer.disconnect();
  }, [hasMore, loadMore]);

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Escape') onClose();
  };

  return createPortal(
    <div className="shader-gallery-backdrop" onClick={onClose}>
      <div className="shader-gallery-modal" onClick={e => e.stopPropagation()} onKeyDown={handleKeyDown}>
        <div className="shader-gallery-header">
          <h3>🖼️ Shader Gallery</h3>
          <button className="shader-gallery-close" onClick={onClose} aria-label="Close">×</button>
        </div>

        <div className="shader-gallery-filters">
          <input
            type="text"
            className="shader-gallery-search"
            placeholder="Search shaders..."
            value={search}
            onChange={e => setSearch(e.target.value)}
            autoFocus
          />
          <select
            className="shader-gallery-category"
            value={category}
            onChange={e => setCategory(e.target.value)}
          >
            <option value="">All Categories ({options.length})</option>
            {categories.map(c => (
              <option key={c} value={c}>{CATEGORY_LABELS[c] || c}</option>
            ))}
          </select>
          <span className="shader-gallery-count">{filtered.length} shader{filtered.length === 1 ? '' : 's'}</span>
        </div>

        <div className="shader-gallery-grid">
          {visible.length === 0 ? (
            <div className="shader-gallery-empty">No shaders match your search.</div>
          ) : (
            visible.map(opt => {
              const thumb = manifest[opt.id];
              return (
                <div
                  key={opt.id}
                  className={`shader-gallery-card${opt.id === value ? ' selected' : ''}`}
                  onClick={() => onSelect(opt.id)}
                  title={opt.name}
                >
                  <div className="shader-gallery-thumb-wrap">
                    {thumb ? (
                      <img
                        src={`./${thumb.thumbnail_url}`}
                        alt={opt.name}
                        className="shader-gallery-thumb"
                        loading="lazy"
                      />
                    ) : (
                      <div className="shader-gallery-thumb-placeholder">
                        <span>{(CATEGORY_LABELS[opt.category] || '✨').slice(0, 2)}</span>
                      </div>
                    )}
                    {(opt.stars !== undefined && opt.stars > 0) && (
                      <div className="shader-gallery-stars-overlay">
                        <ShaderStarRating
                          shaderId={opt.id}
                          stars={opt.stars}
                          ratingCount={opt.ratingCount || 0}
                          onRate={async () => {}}
                          size="small"
                          readonly
                        />
                      </div>
                    )}
                  </div>
                  <div className="shader-gallery-name">{opt.name}</div>
                </div>
              );
            })
          )}
        </div>

        {hasMore && <div ref={sentinelRef} className="shader-gallery-sentinel" />}
      </div>
    </div>,
    document.body
  );
};

export default ShaderGallery;
