// ─── multipass.ts ────────────────────────────────────────────────────────────
// Single authority for multipass detection and pass-count derivation.
// Pass count is derived from the static GRAPH_REGISTRY / MULTIPASS_REGISTRY
// (auto-generated by scripts/buildMultipassRegistry.js) — never hand-authored.
// ─────────────────────────────────────────────────────────────────────────────

import {
  MULTIPASS_REGISTRY,
  hasGraph,
  resolveGraphForShader,
} from '../renderer/multipassRegistry';

export interface MultipassInfo {
  /** Number of distinct shader passes (graph nodes or linear chain length). */
  passCount: number;
}

/**
 * Returns pass-count metadata for a shader id, or null if it is single-pass.
 *
 * For GraphRunner (Tier C) entries the pass count is the number of graph nodes
 * (`graph.nodes.length`), matching the "N-pass" label users see in the UI.
 * For linear Tier B chains the pass count is `totalPasses` from the registry.
 */
export function getMultipassInfo(shaderId: string): MultipassInfo | null {
  if (hasGraph(shaderId)) {
    const graph = resolveGraphForShader(shaderId);
    if (!graph) return null;
    const passCount = graph.nodes.length;
    return passCount > 1 ? { passCount } : null;
  }

  const info = MULTIPASS_REGISTRY[shaderId];
  if (info && info.pass === 1 && info.totalPasses > 1) {
    return { passCount: info.totalPasses };
  }

  return null;
}

/** Returns true when the shader id maps to a multipass chain or graph. */
export function isMultipass(shaderId: string): boolean {
  return getMultipassInfo(shaderId) !== null;
}
