// Default export barrel — named exports live in the modules above.

const wasmBridge = {
  getDiagnostics,
  initWasmRenderer,
  shutdownWasmRenderer,
  loadShader,
  reloadShader,
  loadShaderFromURL,
  reloadShaderFromURL,
  setActiveShader,
  setSlotShader,
  setSlotParams,
  updateSlotParams,
  setSlotMode,
  updateUniforms,
  updateMousePos,
  updateAudioData,
  updateAudioFrequencyBins,
  updateDepthMap,
  setInputSource,
  addRipple,
  clearRipples,
  getFPS,
  getSupportsDeepWorkgroup,
  getColorFormat,
  getSlotState,
  getGPUTimings,
  setRecording,
  isRecordingActive,
  captureFrameDataUrl,
  getAdapterSummary,
  getLastInitErrorStage,
  getLastInitErrorMessage,
  isInitialized,
  uploadImageData,
  uploadVideoFrame,
  resizeCanvas,
  setColorFormat,
  captureFrame,
  takeScreenshot,
  startRecording,
  stopRecording,
  recordAndDownload,
};

export default wasmBridge;
