/**
 * buildMultipassRegistry.js
 *
 * Scans shader_definitions/*.json for multipass metadata and generates
 * src/renderer/multipassRegistry.ts as a static lookup table.
 */

const fs = require('fs');
const path = require('path');

const DEFS_DIR = path.join(__dirname, '..', 'shader_definitions');
const OUT_FILE = path.join(__dirname, '..', 'src', 'renderer', 'multipassRegistry.ts');

const registry = {};

function scan(dir) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      scan(fullPath);
    } else if (entry.name.endsWith('.json')) {
      try {
        const json = JSON.parse(fs.readFileSync(fullPath, 'utf-8'));
        if (json.multipass) {
          registry[json.id] = {
            pass: json.multipass.pass,
            totalPasses: json.multipass.totalPasses,
            nextShader: json.multipass.nextShader || null,
          };
        }
      } catch (e) {
        console.warn(`Skipping ${fullPath}: ${e.message}`);
      }
    }
  }
}

scan(DEFS_DIR);

const lines = [
  `// Auto-generated by scripts/buildMultipassRegistry.js`,
  `// Do not edit manually — re-run the script instead.`,
  ``,
  `export interface MultipassInfo {`,
  `  pass: number;`,
  `  totalPasses: number;`,
  `  nextShader: string | null;`,
  `}`,
  ``,
  `export const MULTIPASS_REGISTRY: Record<string, MultipassInfo> = ${JSON.stringify(registry, null, 2)};`,
  ``,
  `/** Get the next shader in a multipass chain, if any. */`,
  `export function getNextPass(shaderId: string): string | null {`,
  `  return MULTIPASS_REGISTRY[shaderId]?.nextShader ?? null;`,
  `}`,
  ``,
  `/** Check if a shader is the first pass of a multipass chain. */`,
  `export function isMultipassStart(shaderId: string): boolean {`,
  `  const info = MULTIPASS_REGISTRY[shaderId];`,
  `  return info ? info.pass === 1 && info.totalPasses > 1 : false;`,
  `}`,
  ``,
  `/** Resolve the full ordered list of shaders for a given starting ID. */`,
  `export function resolveMultipassChain(startId: string): string[] {`,
  `  const chain: string[] = [];`,
  `  let current: string | null = startId;`,
  `  const seen = new Set<string>();`,
  `  while (current && !seen.has(current)) {`,
  `    seen.add(current);`,
  `    chain.push(current);`,
  `    current = getNextPass(current);`,
  `  }`,
  `  return chain;`,
  `}`,
  ``,
];

fs.writeFileSync(OUT_FILE, lines.join('\n'));
console.log(`Generated ${OUT_FILE} with ${Object.keys(registry).length} entries.`);
