/**
 * buildMultipassRegistry.js
 *
 * Scans shader_definitions/*.json for multipass metadata and generates
 * src/renderer/multipassRegistry.ts as a static lookup table.
 *
 * `buildRegistry({ defsDir, outFile })` is the whole job, exported so tests
 * (and the Graph Lab export check) can run it against a scratch directory.
 */

const fs = require('fs');
const path = require('path');

const DEFS_DIR = path.join(__dirname, '..', 'shader_definitions');
const OUT_FILE = path.join(__dirname, '..', 'src', 'renderer', 'multipassRegistry.ts');

function scanDefinitions(dir, registry, graphRegistry, simRingRegistry) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      scanDefinitions(fullPath, registry, graphRegistry, simRingRegistry);
    } else if (entry.name.endsWith('.json')) {
      try {
        const json = JSON.parse(fs.readFileSync(fullPath, 'utf-8'));
        if (json.multipass?.graph) {
          graphRegistry[json.id] = json.multipass.graph;
        }
        if (json.simRing) {
          simRingRegistry[json.id] = { stateCount: json.simRing.stateCount };
        }
        if (json.multipass?.pass !== undefined) {
          registry[json.id] = {
            pass: json.multipass.pass,
            totalPasses: json.multipass.totalPasses,
            nextShader: json.multipass.nextShader || null,
          };
        }
      } catch (e) {
        console.warn(`Skipping ${fullPath}: ${e.message}`);
      }
    }
  }
}

function renderRegistrySource(registry, graphRegistry, simRingRegistry) {
  const lines = [
    `// Auto-generated by scripts/buildMultipassRegistry.js`,
    `// Do not edit manually — re-run the script instead.`,
    ``,
    `import type { MultipassGraphDef } from './multipassGraph';`,
    `import { getRuntimeGraph } from './runtimeGraphs';`,
    ``,
    `export interface MultipassInfo {`,
    `  pass: number;`,
    `  totalPasses: number;`,
    `  nextShader: string | null;`,
    `}`,
    ``,
    `export const MULTIPASS_REGISTRY: Record<string, MultipassInfo> = ${JSON.stringify(registry, null, 2)};`,
    ``,
    `export const GRAPH_REGISTRY: Record<string, MultipassGraphDef> = ${JSON.stringify(graphRegistry, null, 2)};`,
    ``,
    `/** Opt-in @group(1) sim-ring requests (shader_definitions \`simRing\` field). */`,
    `export const SIM_RING_REGISTRY: Record<string, { stateCount: number }> = ${JSON.stringify(simRingRegistry, null, 2)};`,
    ``,
    `/** Get the next shader in a multipass chain, if any. */`,
    `export function getNextPass(shaderId: string): string | null {`,
    `  return MULTIPASS_REGISTRY[shaderId]?.nextShader ?? null;`,
    `}`,
    ``,
    `/** Check if a shader is the first pass of a multipass chain. */`,
    `export function isMultipassStart(shaderId: string): boolean {`,
    `  const info = MULTIPASS_REGISTRY[shaderId];`,
    `  return info ? info.pass === 1 && info.totalPasses > 1 : false;`,
    `}`,
    ``,
    `/** Resolve the full ordered list of shaders for a given starting ID. */`,
    `export function resolveMultipassChain(startId: string): string[] {`,
    `  const chain: string[] = [];`,
    `  let current: string | null = startId;`,
    `  const seen = new Set<string>();`,
    `  while (current && !seen.has(current)) {`,
    `    seen.add(current);`,
    `    chain.push(current);`,
    `    current = getNextPass(current);`,
    `  }`,
    `  return chain;`,
    `}`,
    ``,
    `/**`,
    ` * Resolve the Tier C graph for a shader id: a runtime graph (the Graph Lab draft,`,
    ` * renderer/runtimeGraphs.ts) wins over the one declared in JSON.`,
    ` */`,
    `export function resolveGraphForShader(shaderId: string): MultipassGraphDef | null {`,
    `  return getRuntimeGraph(shaderId) ?? GRAPH_REGISTRY[shaderId] ?? null;`,
    `}`,
    ``,
    `/** All unique WGSL entry ids referenced by a graph shader. */`,
    `export function getGraphEntryIds(shaderId: string): string[] {`,
    `  const graph = resolveGraphForShader(shaderId);`,
    `  if (!graph) return [];`,
    `  const ids = new Set<string>();`,
    `  for (const node of graph.nodes) {`,
    `    if (node.entry) ids.add(node.entry);`,
    `  }`,
    `  return Array.from(ids);`,
    `}`,
    ``,
    `export function hasGraph(shaderId: string): boolean {`,
    `  return resolveGraphForShader(shaderId) !== null;`,
    `}`,
    ``,
    `/**`,
    ` * Requested sim-ring element count for a shader id or one of its graph entries.`,
    ` * Undefined → the ring's contract default (bind_group1.json oom.defaultStateCount).`,
    ` */`,
    `export function resolveSimRingRequest(shaderId: string): number | undefined {`,
    `  const direct = SIM_RING_REGISTRY[shaderId];`,
    `  if (direct) return direct.stateCount;`,
    `  for (const [ownerId, req] of Object.entries(SIM_RING_REGISTRY)) {`,
    `    if (GRAPH_REGISTRY[ownerId]?.nodes.some((n) => n.entry === shaderId)) return req.stateCount;`,
    `  }`,
    `  return undefined;`,
    `}`,
    ``,
  ];
  return lines.join('\n');
}

/**
 * Scan `defsDir` and (unless `write` is false) regenerate `outFile`.
 * Returns the parsed registries and the generated source.
 */
function buildRegistry({ defsDir = DEFS_DIR, outFile = OUT_FILE, write = true } = {}) {
  const registry = {};
  const graphRegistry = {};
  const simRingRegistry = {};

  scanDefinitions(defsDir, registry, graphRegistry, simRingRegistry);

  const source = renderRegistrySource(registry, graphRegistry, simRingRegistry);
  if (write) fs.writeFileSync(outFile, source);
  return { registry, graphRegistry, simRingRegistry, source, outFile };
}

module.exports = { buildRegistry };

if (require.main === module) {
  const { registry, graphRegistry, simRingRegistry, outFile } = buildRegistry();
  console.log(
    `Generated ${outFile} with ${Object.keys(registry).length} linear + ${Object.keys(graphRegistry).length} graph + ${Object.keys(simRingRegistry).length} sim-ring entries.`,
  );
}
