#!/usr/bin/env python3
"""
Generate the includable WGSL libraries under public/shaders/.

Neither output is hand-maintained; both are derived, so they cannot drift from
their sources:

  _prelude.wgsl  the canonical binding header, from the same
                 scripts/bindgroup_checker.py EXPECTED_BINDINGS the gate checks
                 against and new_shader.py already scaffolds from, plus a
                 `struct Uniforms` built from src/contracts/uniforms_layout.json.

  _hash.wgsl     the hash/noise functions from _hash_library.wgsl with its
                 binding header stripped. The library repeats the 13 bindings so
                 it parses standalone; including that copy alongside _prelude
                 would redeclare every binding, so the includable form must not
                 carry them.

Usage:
    python3 scripts/generate_shader_libs.py           # write both files
    python3 scripts/generate_shader_libs.py --check   # fail if either is stale
"""

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from bindgroup_checker import EXPECTED_BINDINGS, EXPECTED_UNIFORMS_FIELDS  # noqa: E402
from new_shader import CANONICAL_NAMES, build_binding_declarations  # noqa: E402

PROJECT_ROOT = Path(__file__).resolve().parent.parent
PRELUDE_PATH = PROJECT_ROOT / "public" / "shaders" / "_prelude.wgsl"
UNIFORMS_CONTRACT_PATH = PROJECT_ROOT / "src" / "contracts" / "uniforms_layout.json"
HASH_LIBRARY_PATH = PROJECT_ROOT / "public" / "shaders" / "_hash_library.wgsl"
HASH_PATH = PROJECT_ROOT / "public" / "shaders" / "_hash.wgsl"

HASH_HEADER = """\
// ═══════════════════════════════════════════════════════════════════
//  _hash.wgsl — hash / noise library, includable form
//
//  GENERATED by scripts/generate_shader_libs.py from _hash_library.wgsl
//  (its binding header stripped). Do not hand-edit — edit _hash_library.wgsl.
//
//  Use it with:
//      #include "_prelude.wgsl"
//      #include "_hash.wgsl"
//
//  Careful: 1168 catalog shaders already define their own `hash`, `fbm` or
//  `noise`. Including this into one of them redeclares those names and will
//  not compile — delete the shader's own copies in the same edit.
// ═══════════════════════════════════════════════════════════════════
"""

HEADER = """\
// ═══════════════════════════════════════════════════════════════════
//  _prelude.wgsl — canonical binding header
//
//  GENERATED by scripts/generate_shader_libs.py from
//  scripts/bindgroup_checker.py EXPECTED_BINDINGS and
//  src/contracts/uniforms_layout.json. Do not hand-edit:
//  `npm run verify:wgsl-include` regenerates and compares.
//
//  Use it with:
//      #include "_prelude.wgsl"
//
//  Binding 13 (historyTexture) is optional and NOT declared here — the 11
//  shaders that use it declare it themselves, because a shader that binds it
//  without reading it is a validation error.
// ═══════════════════════════════════════════════════════════════════
"""

UNIFORMS_NOTE = """\

// Field meanings are contract, not convention — see src/contracts/uniforms_layout.json.
//   config.x      time in seconds since renderer start (monotonic, NOT delta time)
//   config.y      rippleCount, 0..50 — guard loops with min(u32(u.config.y), 50u)
//   config.zw     render-target resolution in pixels
//   zoom_config.x time again (same value as config.x)
//   zoom_config.yz mouse uv in 0..1, y=0 at the top
//   zoom_config.w mouse_down, pressed when > 0.5
//   zoom_params   user params p1..p4 from the UI sliders
//   ripples[i].xy uv, .z startTime in seconds, .w padding (always 0)
"""


FIELD_COMMENTS = {
    "config": ".x = time (seconds), .y = rippleCount (0-50 active ripples), .zw = resolution (width, height)",
    "zoom_config": ".x = time, .yz = mouse_uv (0-1 canvas: y=0 top), .w = mouse_down (>0.5 = pressed)",
    "zoom_params": ".xyzw = user params p1..p4 (mapped from UI sliders)",
    "ripples": ".xy = ripple uv, .z = startTime (seconds), .w = padding (0)",
}


def build_uniforms_struct() -> str:
    """
    Build `struct Uniforms` from src/contracts/uniforms_layout.json, which is the
    real source of truth for the layout (and is itself gated by
    `npm run verify:uniforms` against UniformBuffer.ts and renderer.h).

    Not scraped from the canonical template: the template now includes the
    prelude, so scraping it would be circular.
    """
    contract = json.loads(UNIFORMS_CONTRACT_PATH.read_text(encoding="utf-8"))
    fields = contract["fields"]

    names = [f["name"] for f in fields]
    if names != list(EXPECTED_UNIFORMS_FIELDS):
        raise RuntimeError(
            f"uniforms_layout.json fields {names} disagree with "
            f"bindgroup_checker.py EXPECTED_UNIFORMS_FIELDS {list(EXPECTED_UNIFORMS_FIELDS)}"
        )

    width = max(len(f"{f['name']}: {f['type']},") for f in fields)
    lines = ["struct Uniforms {"]
    for field in fields:
        decl = f"{field['name']}: {field['type']},"
        comment = FIELD_COMMENTS.get(field["name"])
        lines.append(f"  {decl.ljust(width)}  // {comment}" if comment else f"  {decl}")
    lines.append("};")
    return "\n".join(lines)


def render_prelude() -> str:
    missing = sorted(set(EXPECTED_BINDINGS) - set(CANONICAL_NAMES))
    if missing:
        raise RuntimeError(
            f"new_shader.py CANONICAL_NAMES has no name for binding(s) {missing} — "
            "add them before regenerating the prelude"
        )
    return f"{HEADER}\n{build_binding_declarations()}\n{UNIFORMS_NOTE}\n{build_uniforms_struct()}\n"


def render_hash() -> str:
    """
    Strip the repeated binding header off _hash_library.wgsl, keeping everything
    from its own banner onward.
    """
    library = HASH_LIBRARY_PATH.read_text(encoding="utf-8")
    marker = "//  WGSL Hash Function Library"
    idx = library.find(marker)
    if idx == -1:
        raise RuntimeError(f"{HASH_LIBRARY_PATH} has no '{marker}' banner to cut at")

    # Back up to the start of the banner's opening rule line.
    start = library.rfind("// ═", 0, idx)
    body = library[start if start != -1 else idx :]

    if "@group(0)" in body or "struct Uniforms" in body:
        raise RuntimeError(
            f"{HASH_LIBRARY_PATH}: binding declarations survived the cut — the includable "
            "form must not redeclare what _prelude.wgsl provides"
        )
    return f"{HASH_HEADER}\n{body.rstrip()}\n"


OUTPUTS = [
    (PRELUDE_PATH, render_prelude, "bindgroup_checker.py EXPECTED_BINDINGS"),
    (HASH_PATH, render_hash, "_hash_library.wgsl"),
]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if a committed file is stale")
    args = parser.parse_args()

    failed = False
    for target, render, source in OUTPUTS:
        rendered = render()
        rel = target.relative_to(PROJECT_ROOT)

        if not args.check:
            target.write_text(rendered, encoding="utf-8")
            print(f"Wrote {rel} ({len(rendered)} bytes)")
            continue

        if not target.exists():
            print(f"❌ {rel} is missing", file=sys.stderr)
            failed = True
        elif target.read_text(encoding="utf-8") != rendered:
            print(f"❌ {rel} is out of date with {source}", file=sys.stderr)
            failed = True
        else:
            print(f"✅ {rel} matches {source}")

    if failed:
        print("   regenerate with: python3 scripts/generate_shader_libs.py", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
