#!/usr/bin/env python3
"""
Canonical compute-shader scaffolder for Pixelocity.

Creates a new WGSL file pre-wired to the renderer's bind-group contract.
The binding set is derived from EXPECTED_BINDINGS in bindgroup_checker.py so
it cannot drift from the source of truth.

Usage:
    python scripts/new_shader.py my-new-effect
    python scripts/new_shader.py my-new-effect --category generative
"""

import argparse
import re
import sys
from datetime import datetime
from pathlib import Path

# Import the canonical binding contract from the existing checker.
# Add scripts/ to path so this works regardless of cwd.
_SCRIPTS_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(_SCRIPTS_DIR))
from bindgroup_checker import EXPECTED_BINDINGS, TEMPLATE_FILES  # noqa: E402


PROJECT_ROOT = _SCRIPTS_DIR.parent
SHADERS_DIR = PROJECT_ROOT / "public" / "shaders"
TEMPLATE_PATH = SHADERS_DIR / "_template_canonical_compute.wgsl"

# Canonical variable name for each binding number. The contract in
# bindgroup_checker.py cares about binding NUMBER and TYPE; names are
# flexible, but these are the project-wide conventional identifiers.
CANONICAL_NAMES = {
    0: "u_sampler",
    1: "readTexture",
    2: "writeTexture",
    3: "u",  # the Uniforms instance; the struct itself is always named Uniforms
    4: "readDepthTexture",
    5: "non_filtering_sampler",
    6: "writeDepthTexture",
    7: "dataTextureA",
    8: "dataTextureB",
    9: "dataTextureC",
    10: "extraBuffer",
    11: "comparison_sampler",
    12: "plasmaBuffer",
}


def sanitize_shader_id(raw: str) -> str:
    """Convert a human-readable name to a kebab-case shader id."""
    s = raw.strip().lower()
    s = re.sub(r"[^a-z0-9_\-]+", "-", s)
    s = re.sub(r"-+", "-", s).strip("-")
    if not s:
        raise ValueError(f"Invalid shader id: {raw!r}")
    return s


def build_binding_declarations() -> str:
    """Generate the 13 canonical binding lines from EXPECTED_BINDINGS."""
    lines = []
    for binding_num in sorted(EXPECTED_BINDINGS):
        spec = EXPECTED_BINDINGS[binding_num]
        name = CANONICAL_NAMES[binding_num]
        type_str = spec["type"]
        access = spec["access"]
        storage_class = spec["storage_class"]

        if storage_class == "uniform":
            decl = f"var<uniform> {name}: {type_str}"
        elif storage_class == "storage":
            decl = f"var<storage, {access}> {name}: {type_str}"
        elif access:
            # texture storage
            decl = f"var {name}: {type_str}"
        else:
            decl = f"var {name}: {type_str}"

        lines.append(f"@group(0) @binding({binding_num}) {decl};")

    return "\n".join(lines)


def load_template_stub() -> str:
    """Return the canonical template body (everything after the bindings)."""
    template = TEMPLATE_PATH.read_text(encoding="utf-8")
    # Strip the template-only header comment block and the binding block.
    # Keep everything from the first `struct Uniforms` onward.
    marker = "struct Uniforms"
    idx = template.find(marker)
    if idx == -1:
        raise RuntimeError(
            f"Canonical template missing '{marker}' — rebuild {TEMPLATE_PATH}"
        )
    return template[idx:]


def generate_shader(shader_id: str, category: str | None) -> str:
    """Compose the full WGSL source for a new shader."""
    header = f"""// ═══════════════════════════════════════════════════════════════════════════════
//  {shader_id}
//
//  Category: {category or "uncategorized"}
//  Created: {datetime.now().isoformat()}
//
//  Generated by scripts/new_shader.py from the canonical compute template.
//  Keep binding numbers/types and the Uniforms struct in sync with
//  scripts/bindgroup_checker.py -> EXPECTED_BINDINGS.
// ═══════════════════════════════════════════════════════════════════════════════

{build_binding_declarations()}
"""
    return header + "\n" + load_template_stub()


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Scaffold a new Pixelocity compute shader."
    )
    parser.add_argument("name", help="Human-readable shader name / id")
    parser.add_argument(
        "--category",
        default=None,
        help="Optional category (recorded in header; does not affect WGSL path)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print the generated shader instead of writing it",
    )
    args = parser.parse_args()

    shader_id = sanitize_shader_id(args.name)
    out_path = SHADERS_DIR / f"{shader_id}.wgsl"

    if out_path.name in TEMPLATE_FILES:
        print(f"ERROR: '{out_path.name}' is a reserved template filename.", file=sys.stderr)
        return 1

    if out_path.exists() and not args.dry_run:
        print(f"ERROR: Refusing to overwrite existing file: {out_path}", file=sys.stderr)
        return 1

    source = generate_shader(shader_id, args.category)

    if args.dry_run:
        print(source)
        return 0

    out_path.write_text(source, encoding="utf-8")
    print(f"Created {out_path}")
    print(f"Next: edit the stub effect, then run:")
    print(f"  /root/.cargo/bin/naga {out_path}")
    print(f"  python scripts/wgsl_precommit_gate.py --files {out_path.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
