#!/usr/bin/env bash
# measure_wasm_build_flags.sh — compare WASM binary size for Emscripten flag experiments.
# Run from repo root with emsdk sourced. Results append to wasm_renderer/BUILD_FLAG_EXPERIMENTS.md
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
OUT_MD="$SCRIPT_DIR/BUILD_FLAG_EXPERIMENTS.md"
BUILD_DIR="$SCRIPT_DIR/build/experiments"
mkdir -p "$BUILD_DIR"

if ! command -v emcc &>/dev/null; then
  echo "emcc not found — source emsdk_env.sh first"
  exit 1
fi

export EM_CACHE="${EM_CACHE:-/tmp/emscripten_cache}"
unset EMCC_CFLAGS

SOURCES=(
  "$SCRIPT_DIR/main.cpp"
  "$SCRIPT_DIR/renderer.cpp"
  "$SCRIPT_DIR/device.cpp"
  "$SCRIPT_DIR/resources.cpp"
  "$SCRIPT_DIR/pipeline.cpp"
  "$SCRIPT_DIR/frame.cpp"
  "$SCRIPT_DIR/timing.cpp"
  "$SCRIPT_DIR/audio_depth.cpp"
  "$SCRIPT_DIR/wasm_internal.cpp"
)

EXPORTED="_main,_initWasmRenderer,_shutdownWasmRenderer"
COMMON_FLAGS=(
  -std=c++20 -O2
  --use-port=emdawnwebgpu
  "-I$SCRIPT_DIR"
  "-sEXPORTED_FUNCTIONS=${EXPORTED}"
  -sALLOW_MEMORY_GROWTH=1
  -sGROWABLE_ARRAYBUFFERS=0
  -sNO_EXIT_RUNTIME=1
  -sMODULARIZE=1
  -sEXPORT_NAME=PixelocityWASM
)

build_variant() {
  local name="$1"
  shift
  local out_base="$BUILD_DIR/${name}"
  echo "=== Building variant: $name ==="
  emcc "${COMMON_FLAGS[@]}" "$@" "${SOURCES[@]}" -o "${out_base}.js"
  local wasm_bytes js_bytes
  wasm_bytes=$(wc -c < "${out_base}.wasm")
  js_bytes=$(wc -c < "${out_base}.js")
  echo "$name wasm=${wasm_bytes} js=${js_bytes}"
  echo "| ${name} | ${wasm_bytes} | ${js_bytes} |" >> "$OUT_MD.tmp"
}

DATE_UTC=$(date -u +"%Y-%m-%d %H:%M UTC")
cat > "$OUT_MD.tmp" <<EOF
# WASM build flag experiments

Auto-generated by \`measure_wasm_build_flags.sh\` on ${DATE_UTC}.

| Variant | .wasm bytes | .js bytes |
|---------|------------:|----------:|
EOF

build_variant "baseline-default-memory" -sASYNCIFY
build_variant "initial-memory-64mib" -sASYNCIFY -sINITIAL_MEMORY=67108864
build_variant "no-asyncify-size-only" -sINITIAL_MEMORY=67108864

mv "$OUT_MD.tmp" "$OUT_MD"
echo "Results written to $OUT_MD"
