// Auto-generated by scripts/buildMultipassRegistry.js
// Do not edit manually — re-run the script instead.

import type { MultipassGraphDef } from './multipassGraph';

export interface MultipassInfo {
  pass: number;
  totalPasses: number;
  nextShader: string | null;
}

export const MULTIPASS_REGISTRY: Record<string, MultipassInfo> = {
  "spectrogram-displace-pass1": {
    "pass": 1,
    "totalPasses": 2,
    "nextShader": "spectrogram-displace-pass2"
  },
  "spectrogram-displace-pass2": {
    "pass": 2,
    "totalPasses": 2,
    "nextShader": null
  },
  "vortex-pass1": {
    "pass": 1,
    "totalPasses": 2,
    "nextShader": "vortex-pass2"
  },
  "vortex-pass2": {
    "pass": 2,
    "totalPasses": 2,
    "nextShader": null
  },
  "pyramid-bandprocess-pass2": {
    "pass": 2,
    "totalPasses": 3,
    "nextShader": "pyramid-composite-pass3"
  },
  "pyramid-composite-pass3": {
    "pass": 3,
    "totalPasses": 3,
    "nextShader": null
  },
  "pyramid-downsample-pass1": {
    "pass": 1,
    "totalPasses": 3,
    "nextShader": "pyramid-bandprocess-pass2"
  },
  "aurora-rift-2-pass1": {
    "pass": 1,
    "totalPasses": 2,
    "nextShader": "aurora-rift-2-pass2"
  },
  "aurora-rift-2-pass2": {
    "pass": 2,
    "totalPasses": 2,
    "nextShader": null
  },
  "aurora-rift-pass1": {
    "pass": 1,
    "totalPasses": 2,
    "nextShader": "aurora-rift-pass2"
  },
  "aurora-rift-pass2": {
    "pass": 2,
    "totalPasses": 2,
    "nextShader": null
  },
  "liquid-optimized-pass1": {
    "pass": 1,
    "totalPasses": 2,
    "nextShader": "liquid-optimized-pass2"
  },
  "liquid-optimized-pass2": {
    "pass": 2,
    "totalPasses": 2,
    "nextShader": null
  },
  "liquid-pass1": {
    "pass": 1,
    "totalPasses": 2,
    "nextShader": "liquid-pass2"
  },
  "liquid-pass2": {
    "pass": 2,
    "totalPasses": 2,
    "nextShader": null
  },
  "tone-histogram-apply": {
    "pass": 2,
    "totalPasses": 2,
    "nextShader": null
  },
  "digital-glitch-pass1": {
    "pass": 1,
    "totalPasses": 2,
    "nextShader": "digital-glitch-pass2"
  },
  "digital-glitch-pass2": {
    "pass": 2,
    "totalPasses": 2,
    "nextShader": null
  },
  "quantum-foam-pass1": {
    "pass": 1,
    "totalPasses": 3,
    "nextShader": "quantum-foam-pass2"
  },
  "quantum-foam-pass2": {
    "pass": 2,
    "totalPasses": 3,
    "nextShader": "quantum-foam-pass3"
  },
  "quantum-foam-pass3": {
    "pass": 3,
    "totalPasses": 3,
    "nextShader": null
  },
  "rd-on-video-pass1": {
    "pass": 1,
    "totalPasses": 3,
    "nextShader": "rd-on-video-pass2"
  },
  "rd-on-video-pass2": {
    "pass": 2,
    "totalPasses": 3,
    "nextShader": "rd-on-video-pass3"
  },
  "rd-on-video-pass3": {
    "pass": 3,
    "totalPasses": 3,
    "nextShader": null
  },
  "ripple-tank-pass2": {
    "pass": 2,
    "totalPasses": 3,
    "nextShader": "ripple-tank-pass3"
  },
  "ripple-tank-pass3": {
    "pass": 3,
    "totalPasses": 3,
    "nextShader": null
  },
  "ripple-tank": {
    "pass": 1,
    "totalPasses": 3,
    "nextShader": "ripple-tank-pass2"
  },
  "sim-fluid-feedback-field": {
    "pass": 1,
    "totalPasses": 3,
    "nextShader": null
  }
};

export const GRAPH_REGISTRY: Record<string, MultipassGraphDef> = {
  "quantum-foam-pass1": {
    "maxPassesPerFrame": 8,
    "nodes": [
      {
        "id": "integrate",
        "entry": "quantum-foam-pass1",
        "reads": [
          "dataC"
        ],
        "writes": [
          "dataA"
        ]
      },
      {
        "id": "composite",
        "entry": "quantum-foam-pass2",
        "reads": [
          "dataA"
        ],
        "writes": [
          "dataB"
        ]
      },
      {
        "id": "render",
        "entry": "quantum-foam-pass3",
        "reads": [
          "dataB"
        ],
        "writes": [
          "color"
        ]
      }
    ]
  },
  "wave-tank": {
    "maxPassesPerFrame": 8,
    "nodes": [
      {
        "id": "step",
        "entry": "wave-step",
        "reads": [
          "dataC"
        ],
        "writes": [
          "dataA"
        ],
        "repeat": 3
      },
      {
        "id": "inject",
        "entry": "wave-inject",
        "reads": [
          "dataA"
        ],
        "writes": [
          "dataB"
        ]
      },
      {
        "id": "render",
        "entry": "wave-render",
        "reads": [
          "dataB"
        ],
        "writes": [
          "color",
          "dataA"
        ]
      }
    ]
  }
};

/** Get the next shader in a multipass chain, if any. */
export function getNextPass(shaderId: string): string | null {
  return MULTIPASS_REGISTRY[shaderId]?.nextShader ?? null;
}

/** Check if a shader is the first pass of a multipass chain. */
export function isMultipassStart(shaderId: string): boolean {
  const info = MULTIPASS_REGISTRY[shaderId];
  return info ? info.pass === 1 && info.totalPasses > 1 : false;
}

/** Resolve the full ordered list of shaders for a given starting ID. */
export function resolveMultipassChain(startId: string): string[] {
  const chain: string[] = [];
  let current: string | null = startId;
  const seen = new Set<string>();
  while (current && !seen.has(current)) {
    seen.add(current);
    chain.push(current);
    current = getNextPass(current);
  }
  return chain;
}

/** Resolve Tier C graph for a shader id, if declared in JSON. */
export function resolveGraphForShader(shaderId: string): MultipassGraphDef | null {
  return GRAPH_REGISTRY[shaderId] ?? null;
}

/** All unique WGSL entry ids referenced by a graph shader. */
export function getGraphEntryIds(shaderId: string): string[] {
  const graph = GRAPH_REGISTRY[shaderId];
  if (!graph) return [];
  const ids = new Set<string>();
  for (const node of graph.nodes) {
    if (node.entry) ids.add(node.entry);
  }
  return Array.from(ids);
}

export function hasGraph(shaderId: string): boolean {
  return shaderId in GRAPH_REGISTRY;
}
