// Auto-generated by scripts/buildMultipassRegistry.js
// Do not edit manually — re-run the script instead.

export interface MultipassInfo {
  pass: number;
  totalPasses: number;
  nextShader: string | null;
}

export const MULTIPASS_REGISTRY: Record<string, MultipassInfo> = {
  "aurora-rift-2-pass1": {
    "pass": 1,
    "totalPasses": 2,
    "nextShader": "aurora-rift-2-pass2"
  },
  "aurora-rift-2-pass2": {
    "pass": 2,
    "totalPasses": 2,
    "nextShader": null
  },
  "aurora-rift-pass1": {
    "pass": 1,
    "totalPasses": 2,
    "nextShader": "aurora-rift-pass2"
  },
  "aurora-rift-pass2": {
    "pass": 2,
    "totalPasses": 2,
    "nextShader": null
  },
  "quantum-foam-pass1": {
    "pass": 1,
    "totalPasses": 3,
    "nextShader": "quantum-foam-pass2"
  },
  "quantum-foam-pass2": {
    "pass": 2,
    "totalPasses": 3,
    "nextShader": "quantum-foam-pass3"
  },
  "quantum-foam-pass3": {
    "pass": 3,
    "totalPasses": 3,
    "nextShader": null
  },
  "sim-fluid-feedback-field": {
    "pass": 1,
    "totalPasses": 3,
    "nextShader": null
  }
};

/** Get the next shader in a multipass chain, if any. */
export function getNextPass(shaderId: string): string | null {
  return MULTIPASS_REGISTRY[shaderId]?.nextShader ?? null;
}

/** Check if a shader is the first pass of a multipass chain. */
export function isMultipassStart(shaderId: string): boolean {
  const info = MULTIPASS_REGISTRY[shaderId];
  return info ? info.pass === 1 && info.totalPasses > 1 : false;
}

/** Resolve the full ordered list of shaders for a given starting ID. */
export function resolveMultipassChain(startId: string): string[] {
  const chain: string[] = [];
  let current: string | null = startId;
  const seen = new Set<string>();
  while (current && !seen.has(current)) {
    seen.add(current);
    chain.push(current);
    current = getNextPass(current);
  }
  return chain;
}
